before_script:
  - psql -c 'create database wtforms_alchemy_test;' -U postgres


language: python
python:
  - 2.7
install:
  - pip install -q -e . --use-mirrors
  - pip install -r requirements-dev.txt
script:
  - python setup.py test
