before_script:
  - psql -c 'create database wtforms_alchemy_test;' -U postgres


language: python
python:
  - 2.7

env:
  matrix:
    - WTFORMS=1.0.5

install:
  - pip install WTForms==$WTFORMS
  - pip install -e ".[test]"

script:
  - python setup.py test -s
